---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
        - name: redis-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sleep"]
          args: ["infinity"]
          env:
            - name: REDIS_PASSWORD
              value: "{{ .Values.redis.password }}"
